[package]
name = "cdadd"
version = "0.1.3"
edition = "2021"

[dependencies]
filesan = "0.2.0"
flexi_logger = "0.30.1"
log = "0.4.27"
pareg = "0.9.1"
rust-ini = "0.21.1"
termal = { version = "2.1.2", features = ["readers"] }
thiserror = "2.0.12"
